### ISSUE TITLE
🧹 Prevent new folder creation on `myst clean`

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/mystjs#107]
The `webObjectFileFactory` aggressively copies notebook outputs to files very early in the processing stage (i.e. when going from notebook file to pre-processed mdast). This is opposed to markdown processing where everything is kept in memory at that stage.

This only becomes apparent when running `myst clean`: markdown and notebook files are processed to read frontmatter and find all the exports which need cleaning. Just in doing that the `_build/site/public/_static` folder is created and some notebook files are copied over...

Likely the solution to this is modifying the `webObjectFileFactory`, maybe aligning more with how markdown files are processed? or maybe just making the file copying happen a bit later?

**Comment by rowanc1** [comment]
This is related to #104, which some in progress work is starting to remove dependence on blocks, and have a smaller surface area for dealing with notebooks.
