### ISSUE TITLE
Place header anchors to the right of the header instead of the left

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystjs#120]
### Context

Currently our header anchors are to the left of the header. They exist in the "within-page left margin". However, this means that in some cases the anchor overlaps with other UI elements like the primary sidebar scrollbar:

For example:

![chrome_LmVEEQH3Ps](https://user-images.githubusercontent.com/1839645/210373186-58e7e3ba-3083-4eab-89f8-ffffdb300d18.gif)

As an anecdote, I've also found that it is tricky to get the UX right when putting things in the "in between" spaces of the page, and have instead opted to try and make UI elements flow with the content when possible.

### Proposal

I'd suggest we move header anchors to the right of the headers rather than be to the left. They'd flow with the header content so we'd know they will always be visible on the page.

**Comment by rowanc1** [comment]
Thanks, this sounds great for headers, it also is not great in the demo components, which is something I have been thinking on how to deal with.

Do you have thoughts/experience on where caption anchors and equation anchors should go?

![target-anchors](https://user-images.githubusercontent.com/913249/210394877-d3379819-ea2e-4b59-a6a7-636d468088a2.gif)

**Comment by choldgraf** [comment]
Another thing I realized: because the anchors are to the left, they are not accessible on mobile! For example 

![Screenshot_20230129-180248](https://user-images.githubusercontent.com/1839645/215343100-44edc839-25ef-488b-89e9-d8dac9d66de7.png)

**Comment by rowanc1** [comment]
I had a conversation with @mikedoesux and I think the figure/equation references we can fix as direct links (i.e. from "`Figure 1`:" or "(`1`)", with the code bit being the link + hover tooltip on desktop), which means the title is the only one we need to fix here, and that can just be inline!

**Comment by rowanc1** [comment]
I have fixed this up and will release in the next few days! Works better in JupyterLab as well.

![hash-links](https://user-images.githubusercontent.com/913249/216785411-c1d5ed96-9df2-4065-a987-709077a7df6f.gif)

**Comment by choldgraf** [comment]
Linking the number for equations is nice 👌

**Comment by rowanc1** [comment]
Yeah, I really like how simple it is. Works for figures, tables and program listings as well!!
