### ISSUE TITLE
Check for nodejs 16 or 18 and raise a helpful error message if not found

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystjs#127]
I tried following the installation instructions and got a weird error when running any myst commands. I looked deeper and realized it was because I was running `nodejs` 14. The [installing prerequisites](https://myst.tools/docs/mystjs/installing-prerequisites) section explained that I needed node 16+, but because it came _after_ the "install myst" section, I missed it.

I'd suggest either:

1. Check for the nodejs version and raise an error w/ a helpful message, rather than waiting for node to choke.
2. Moving the installation pre-requisites before the "install myst" section

**Comment by rowanc1** [comment]
Good call on bringing the pre-reqs higher in the docs. I also think that adding a way to install this through conda might be good. We tried last year but couldn't figure it out.

Node 14 end-of-life is in [~4 months](https://github.com/nodejs/release#release-schedule), and the current features we are using aren't supported in 14, so even showing the error message is hard. We do raise helpful errors as soon as you get to 16+!! Node 14 also doesn't support the "engines" field in the package.json, so the install process doesn't even warn... :(

I think for now, I will focus attention on improving docs, and if you have any experts in conda you know, that would be amazing to get an instal through more familiar channels for python users.

**Comment by rowanc1** [comment]
Updated the docs, going to leave this there for now!

![image](https://user-images.githubusercontent.com/913249/213960234-67380be9-8924-45a7-8f52-7ac5337ee552.png)

I think it may be worth seeing how hard supporting 14 is when we work on some more of the packaging work. Going to think about that more in #139, where we could have some better messages in a python wrapper.

**Comment by choldgraf** [comment]
Re: supporting earlier versions of node, my 2 cents is that it is a better use of time to find a way to install Myst cli via python (or R etc) without directly invoking node. I think the vast majority of researchers and educators have never used node and I worry this may be pretty confusing for them. Python is OK because there are a ton of "learn python for science" resources in academia, but very few people learn node or JS. So I guess my point is that I suspect there are few users that really want to use legacy node, and many users that have no idea what node is at all 🙂
