### ISSUE TITLE
Document colonFences

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystjs#128]
### Context

Colon fences aren't supported out of the box, but it seems that they are supported some way or another:

https://github.com/executablebooks/mystjs/blob/4a6822d6b4190ce1927c138c85735b1da4b8be30/packages/mystjs/tests/colonFences.spec.ts#L3

However I couldn't see any mention of colon fences in the docs, or extensions in general.

### Proposal

As a start, perhaps we could:

1. Add a section about MyST extensions and how to activate them in myst.js
2. Document how to activate colonFences as the first extension to show off.

**Comment by rowanc1** [comment]
Can you check the version of myst (`myst - v`) the latest should be on `0.1.5`, colon fences are enabled by default, including some basics to render qmd-style syntax:

![image](https://user-images.githubusercontent.com/913249/211210756-6bc10aa6-9eb3-4ba2-9309-5127e9d9b094.png)

My thinking on colon fences has evolved a bit: I think they should be the documented syntax when the body of the directive is markdown (e.g. admonitions, containers, not math/code). That way all sorts of renderers can still do a decent job. This also brings things a bit more inline with other syntax like [qmd/pandoc](https://quarto.org/docs/authoring/callouts.html#markdown-syntax).

**Comment by rowanc1** [comment]
I suspect that your myst-cli was out of date. Please reopen if this issue remains!!

I have started embracing colon fences more in the documentation, feedback welcome!! For example:

- https://myst.tools/docs/mystjs/admonitions
- https://myst.tools/docs/mystjs/syntax-overview#directives

![image](https://user-images.githubusercontent.com/913249/213964350-321137d8-b0ca-4af4-a0c4-3a4f4b87ac14.png)
