### ISSUE TITLE
myst-transforms, myst-to-tex, myst-to-jats was not found in your node_modules

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystjs#144]
I just tried to build a local jupyter book site with `myst-cli`, and got these errors:

```
The path "myst-transforms" is imported in ../theme-base/packages/myst-to-react/src/myst.tsx but "myst-transforms" was not found in your node_modules. Did you forget to install it?
The path "myst-to-tex" is imported in ../theme-base/packages/myst-to-react/src/myst.tsx but "myst-to-tex" was not found in your node_modules. Did you forget to install it?
The path "myst-to-jats" is imported in ../theme-base/packages/myst-to-react/src/myst.tsx but "myst-to-jats" was not found in your node_modules. Did you forget to install it?
```

I'm running myst-cli v0.1.5 (what was installed after running `npm update -g myst-cli`.

**Comment by rowanc1** [comment]
This is a spurious warning that has leaked through due to the underlying package changing their message slightly!

**Comment by rowanc1** [comment]
Aiming to do another release on Monday or Tuesday that should fix these up, thanks @choldgraf for the report. Looking forward to more. :)
