### ISSUE TITLE
Scope content directory

### ISSUE THREAD

**Issue by matthewturk** [executablebooks/mystjs#156]
### Context

I'm in the process of migrating a project to MySTjs from another system, and one of the things I'd like to try to do is retain as much of the file-directory scoping that I've been using so far.  For example, right now I have:

```
content/*.md
scripts/
_build/
...some-other-metadata-files...
```

I think it makes the most sense for this particular use case to retain the top-level location of `myst.yml` but specify that my content is all located under the `content` directory.

### Proposal

Being able to add to the top-level `myst.yml` a configuration parameter like `contentdir` would be very helpful!

**Comment by fwkoch** [comment]
@matthewturk - Thanks for opening this! Your use case certainly makes sense - I have a couple suggestions.

### Separate the `project` and `site` configs.

If you look at the [configuration quickstart docs](https://myst.tools/docs/mystjs/quickstart-myst-websites#configuration), the `myst.yml` file has two parts: (1) project configuration which is closely tied to your content, including [authorship, licensing, etc](https://myst.tools/docs/mystjs/frontmatter#available-frontmatter-fields), and (2) site configuration which pulls together projects and templates into a single root location for building a website. These two parts can live in different `myst.yml` files.

This means you can create a `content/myst.yml` file with project frontmatter:
```yaml
version: 1
project:
  title: ...
  authors: ...
  ...
```

And a root-level `myst.yml` file that references the project in the `content` subfolder:
```yaml
version: 1
site:
  template: book-theme
  projects:
    - slug: my-content
      path: content
  ...
```

Doing this will keep the `_build` directory at the root level, but everything else outside of the `content` folder will be ignored.

### Use and explicit `_toc.yml`

You may also [generate a table of contents](https://myst.tools/docs/mystjs/table-of-contents), then edit that to include only the content you are interested in. This approach is more heavy-handed; every file you want to include must be explicitly listed, you cannot add an entire folder with a wildcard or something. Then any new files you create must be manually added to the ToC.

---

Does one of those solutions work for you? Sounds like the first one is probably closer to what you want... Let us know!

**Comment by rowanc1** [comment]
Thanks @fwkoch  --- also think that your explanation as is should go in the docs. :) Tagging it over in #153, I think having another guide that walks through adding more complex/multiple projects would be good.

**Comment by fwkoch** [comment]
I added a bit about splitting project and site configs to the docs with #177 

Closing this for now, but feel free to re-open if you are unsatisfied @matthewturk !

**Comment by matthewturk** [comment]
I meant to close it -- thanks for taking the initiative!  I am going to use this as a first start, and if it doesn't work I will come back (but I see no reason your suggestion won't be sufficient.)
