### ISSUE TITLE
Changing bib files does not bust cache

### ISSUE THREAD

**Issue by drscotthawley** [executablebooks/mystjs#157]
### Describe the bug

**context**
When I follow the [instructions for performing citations](https://myst.tools/docs/mystjs/citations) ("you can include a *.bib file or files in the same directory as your content directory for the project. These will provide the reference keys for that project.")

and add in my document
```
my sentence that ends with a citation {cite:p}`HEAR`
```
in my MyST markdown document,  for which I have the front-matter

```yaml 
bibliography:
  - mybibfile.bib
```
and the file `mybibfile.bib` in the same directory as the .md file, and the key "HEAR" is defined in the .bib file (i.e. "@misc{HEAR,....}")

**expectation**
I expected the proper citation to occur.

**bug**
But instead an error message happens
Here's an error message I ran into...

```console
⚠️  Could not find citation: HEAR in 01-paper.md.
```

**problem**
This is a problem for people doing using BibTeX because MyST should be able to find the keys defined in the .bib file, but otherwise we just get an error. 

### Reproduce the bug

Define a key in a .bib file, e.g. 

```tex
@misc{HEAR,
  doi = {10.48550/ARXIV.2203.03022},
  
  url = {https://arxiv.org/abs/2203.03022},
  
  author = {Turian, Joseph and Shier, Jordie and Khan, Humair Raj and Raj, Bhiksha and Schuller, Björn W. and Steinmetz, Christian J. and Malloy, Colin and Tzanetakis, George and Velarde, Gissel and McNally, Kirk and Henry, Max and Pinto, Nicolas and Noufi, Camille and Clough, Christian and Herremans, Dorien and Fonseca, Eduardo and Engel, Jesse and Salamon, Justin and Esling, Philippe and Manocha, Pranay and Watanabe, Shinji and Jin, Zeyu and Bisk, Yonatan},
  
  keywords = {Sound (cs.SD), Artificial Intelligence (cs.AI), Machine Learning (cs.LG), Audio and Speech Processing (eess.AS), Machine Learning (stat.ML), FOS: Computer and information sciences, FOS: Computer and information sciences, FOS: Electrical engineering, electronic engineering, information engineering, FOS: Electrical engineering, electronic engineering, information engineering},
  
  title = {HEAR: Holistic Evaluation of Audio Representations},
  
  publisher = {arXiv},
  
  year = {2022},
  
  copyright = {Creative Commons Attribution 4.0 International}
}
```

2. put that in a .bib file
3. reference that .bib file in the YAML front matter of your Myst Markdown file
4. try to cite it using the instrucitons provided 

As an alternative, I can successfully just refer to the DOI, e.g. `[HEAR](https://doi.org/10.48550/arXiv.2203.03022)`, but there are some references I plan to use which may not have DOIs.  Thus I want to become proficient in using my BibTeX file in addition the DOI method. 

--

### List your environment

```
$ jupyter book --version
Jupyter Book      : 0.13.1
External ToC      : 0.2.4
MyST-Parser       : 0.15.2
MyST-NB           : 0.13.2
Sphinx Book Theme : 0.3.3
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.13
```

**Comment by drscotthawley** [comment]
I'd also like a Feature Request but will wait until this is resolved.  
The Feature is: Numbered citations, please! I don't want "(Turian et al, 2017)", I want "[1]".

**Comment by drscotthawley** [comment]
**UPDATE:** 
Ok, I think I found the problem: .bib files are apparently (behaviour-wise) only scanned for at the very beginning of `myst start`, and never again. 

But I added the `.bib` stuff *in the course of editing the .md file*, during which `myst start` was still running.  But for some reason when it re-generates the website it never bothers to check for (new) .bib files. 

I discovered this by killing the myst process and restarting it.  After I restarted it, it had no problem finding my citation keys. 

So.. Next up: Numerical citations please! :-)

**Comment by rowanc1** [comment]
I have updated the issue title to say that changing the bib files doesn't bust the cache. This is also currently the case for the table of contents -- we added caching a few weeks ago to improve speed, and are still working through some of the unintended consequences of that!!

I will open a new issue to track the numbered citations.

**Comment by rowanc1** [comment]
@drscotthawley the fix for bibtex reload will be released later this week!
