### ISSUE TITLE
Support "Hide cell contents" directives

### ISSUE THREAD

**Issue by matthewturk** [executablebooks/mystjs#160]
### Context

I'd like to specify some cells in jupyter notebooks as being hidden, using either the YAML frontmatter options or using the cell metadata tags, as specified in the [MySTNB documentation](https://myst-nb.readthedocs.io/en/v0.14.0/render/hiding.html).  At present, neither suppresses when using `.ipynb` as content sources and `myst start` to serve.

### Proposal

I think either allowing these configuration options, *or* support direct transclusion of figures from notebooks would be sufficient to enable generating figures/diagrams using jupyter notebooks.  (i.e., not a thumbnail, but a direct embedding of the cell outputs using figure references.)  My particular use case is where I'm doing some internal API manipulations to expose behavior and methods, so the underlying code may just serve to confuse.

**Comment by fwkoch** [comment]
@matthewturk - thanks for the issue, and great timing!

In the latest release we added functionality to reference notebook output as a figure.

First, label the cell using cell metadata like so (following [the style of quarto](https://quarto.org/docs/reference/cells/cells-jupyter.html)):

```python
#| label: my-cell
5 + 5
```

Then you can reference the label in a figure directive:

````
```{figure} #my-cell

This figure shows the output of some simple math. It will also work with images, html outputs, etc!
```
````

Doing so will embed the output as a figure. Sounds like this matches the second option in your proposals? There isn't a ton of flexibility yet, e.g. you can't hide cells directly in the notebook, only when including elsewhere. Give it a try and let us know what else you need to make this any more usable!

**Comment by matthewturk** [comment]
Thank you!  What I was missing was indeed referencing it using `{figure} #my-cell` -- I had been trying to do it using the inline references, not realizing that I could specify a label as the argument to the `{figure}` directive.  That's awesome!

I'm fine with closing the issue, although if you want to use it to track getting cell metadata like mystnb that's OK with me too.

**Comment by fwkoch** [comment]
I added info about figures referencing cell output to the docs in #177 

I'll close this now, and we can open a new issue when we start thinking more about cell metadata.

**Comment by davidtrem** [comment]
Is there any plan to support myst-nb cell tags like hide-input, remove-cell... 
like mentioned in https://github.com/executablebooks/myst-theme/issues/50  ?
This is a roadblock for me today.
Is there any (easy) way around it (i.e. remove notebook cell tagged with remove-cell during pdf or html build) ?
