### ISSUE TITLE
Admonition titles that span multiple lines aren't indented properly on mobile 

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystjs#169]
On mobile, if the admonition title spans multiple lines then the text on the bottom line doesn't have the proper indentation. For example:

![Screenshot_20230129-164940](https://user-images.githubusercontent.com/1839645/215338249-08b4bacc-11ee-4954-94d6-d05e681233ef.png)

The text also seems to be slightly off center vertically

![Screenshot_20230129-165504](https://user-images.githubusercontent.com/1839645/215338469-66eab9a6-307f-495f-acdf-c87f8f5778dd.png)

**Comment by rowanc1** [comment]
Thanks -- will take a look soon! I may also remove the "Click to show" helper text on mobile? Any thoughts on that?

- [ ] Put the title contents in a flex box
- [ ] Fix alignment issues

**Comment by choldgraf** [comment]
My suggestion is to follow what other projects use for collapsed admonition. It is certainly another thing taking up visual space, and another thing to translate if we ever get to internationalization, but I don't know if it is a best practice in accessibility or not so I don't have strong opinions. What do the big players like Docusaurus or quarto do? I bet that we are ok just following suit

**Comment by rowanc1** [comment]
I have improved the admonitions and will re-release shortly!

You can play with the component here:
https://curvenote.github.io/theme-base/?path=/docs/components-admonitions--simple-admonition

Thanks again for the report. :)

![admonition-docs](https://user-images.githubusercontent.com/913249/216470177-d10d2956-20b9-40b6-808f-613e661b7c61.gif)
