### ISSUE TITLE
https://myst.tools not available from work network

### ISSUE THREAD

**Issue by jkmacc-LANL** [executablebooks/mystjs#172]
### What version of `mystjs` are you using?

not a myst CLI issue

### How did you install myst?

npm

### What operating system are you using?

Mac

### Which area is this feature request for?

Website User Interface

### Describe the Bug

The myst.tools website isn't reachable on my work network (Firefox, Mac).  At a recent [MyST webinar](https://youtu.be/NxSNVt9XsCI), it was mentioned in the chat that others were also having the same issue, and that it may have been related to myst.tools being on a "domain squatting" list that some corporate networks use.  @rowanc1 made note of it during the webinar, so this issue is just to keep track of it.  

Thank you for all your great work!

```
Secure Connection Failed

An error occurred during a connection to myst.tools. PR_CONNECT_RESET_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by rowanc1** [comment]
Thanks for the report @jkmacc-LANL - I have also heard someone from the NIH being unable to access the site. Not great.

I wonder if it is a blanket block on all `.tools` domains? I am not sure if you can find that out?

I don't think there is any issue with out SSL certificate, or hosting. All are pretty standard.

@choldgraf we may want to think about getting a `.org` in addition, and using the .tools as a redirect? I very much want folks in the us gov to be able to see the docs!

**Comment by jkmacc-LANL** [comment]
I don't know any other `.tools` sites, but I'm willing to try to try if you have one OTOH.

**Comment by rowanc1** [comment]
All website links have now been moved over. @jkmacc-LANL please let us know if this remains an issue for accessing the documentation.

The templates API will be fixed in the next release!

**Comment by jkmacc-LANL** [comment]
Huzzah!  The site works 😄   Thank you!
