### ISSUE TITLE
newlines in table cells results in invalid LaTeX

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystjs#200]
### What version of `mystjs` are you using?

0.1.11

### How did you install myst?

npm

### What operating system are you using?

Mac

### Which area is this feature request for?

Export: LaTeX or PDF

### Describe the Bug

The following is a minimal example:

![image](https://user-images.githubusercontent.com/1473646/217566357-dded8e0f-2be1-4c95-bb96-5fa5c086652a.png)

the newline causes an issue. AFAIK the tabular environment does not support any newline breaks in cells, whether they are header, or bolded, or not.

[try it out here](https://myst-tools.org/sandbox?tab=latex&myst=YABgAGAAewBsAGkAcwB0AC0AdABhAGIAbABlAH0AIABGAG8AcwBmAG8AcgBjAG8AbgBjAGUAbgB0AHIAYQB0AGkAZQAgAGkAbgAgAGgAZQB0ACAAZAByAGEAaQBuAGEAZwBlAHcAYQB0AGUAcgAgAHYAYQBuACAAZABlACAAQwBEAC0AIABlAG4AIABSAEQALQB2AGUAbABkAGUAbgAuAAoAOgBoAGUAYQBkAGUAcgAtAHIAbwB3AHMAOgAgADEACgA6AG4AYQBtAGUAOgAgAHEAegBrAE8AVQBHAFAAQQBtADkACgAKACoAIAAtACAAKgAqAEQAYQB0AHUAbQAqACoACgAKACAAIAAtACAAKgAqAEwAbwBjAGEAdABpAGUAKgAqAAoACgAgACAALQAgACoAKgBPAHAAbABvAHMAYgBhAGEAcgAgAFAAIABcAAoAIAAgACAAIAAoAGcAZQBmAGkAbAB0AGUAcgBkACAAbQBvAG4AcwB0AGUAcgApACoAKgAKAAoAIAAgACAAIAAqACoAXABbAG0AZwAuAGwAKgAqACAAewBzAHUAcAB9AGAAXAAtADEAYAAqACoAXABdACoAKgAKAAoAIAAgAC0AIAAqACoAVABvAHQAYQBhAGwAIABQACAAXAAKACAAIAAgACAAKABvAG4AZwBlAGYAaQBsAHQAZQByAGQAIABtAG8AbgBzAHQAZQByACkAKgAqAAoACgAgACAAIAAgACoAKgBcAFsAbQBnAC4AbAAqACoAewBzAHUAcAB9AGAAXAAtADEAYAAqACoAXABdACoAKgAKAAoAKgAgAC0AIAAwADcALwAwADUALwAyADAAMgAyAAoACgAgACAALQAgAGEAZgB2AG8AZQByACAAQwBEAAoACgAgACAALQAgADEAXAAuADgAMwAKAAoAIAAgAC0AIAAxAFwALgA4ADUACgBgAGAAYAA%3D)

### Expected Behavior

A `\\` should never be rendered inside a tabular environment

**Comment by rowanc1** [comment]
Fixed in 0.1.19! 🚀

![image](https://user-images.githubusercontent.com/913249/226794309-134cc9ce-3cfa-4f2c-9dbb-3698debec470.png)
