### ISSUE TITLE
Frames around screenshots that contain text

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystjs#213]
### Which area is this feature request for?

Website User Interface

### Describe the feature you'd like to request

In the docs, there are some screenshots of text, e.g. here
https://myst-tools.org/docs/mystjs/quickstart-myst-documents#use-myst-markdown
and it's not easy to see where the text ends and the screenshot starts:
<kbd>
<img width="860" alt="image" src="https://user-images.githubusercontent.com/44469195/218838542-139765df-d196-463b-b888-dd7c4c487f5c.png">
</kbd>

### Describe the solution you'd like

Frames would be nice to improve readability!
In GitHub, there is the option to add a frame with kbd:

```
<kbd>
<img  src="https://user-images.githubusercontent.com/44469195/218838697-42ca96ae-5146-4aca-b19a-4c47ca7c73aa.png">
</kbd>
```
renders to 
<kbd>
<img  src="https://user-images.githubusercontent.com/44469195/218838697-42ca96ae-5146-4aca-b19a-4c47ca7c73aa.png">
</kbd>

vs. without frame:
<img  src="https://user-images.githubusercontent.com/44469195/218838697-42ca96ae-5146-4aca-b19a-4c47ca7c73aa.png">

Is there a way to add image frames in myst as well?

Additional note: I first posted this issue by accident in the [myst-nb repo](https://github.com/executablebooks/MyST-NB/issues/472)
From the mystjs webpage, clicked on the [GitHub icon](https://myst-tools.org/) on the top right, which lead me to the organization page: https://github.com/executablebooks, but the mystjs is not pinned there. 
Maybe the mystjs repo can be pinned as well to improve discoverability?

**Comment by rowanc1** [comment]
Thanks @kolibril13! Love the style suggestion, and agree that the images of docs-in-docs are pretty hard.

@mikedoesux - you have also been doing some experimentation with making figures standout, do you have some suggestions here?

For navigating the repos, @choldgraf what are your thoughts of getting a version of https://github.com/executablebooks/.github/pull/30 merged, I think we do need a better "welcome" experience on the front page of our github that gives folks a bit of orientation of all of the projects we have going on in this organization.

On the website side, I will update the github link to change based on the page you are on (e.g. in the docs for a specific project, you should probably just land on that project).

**Comment by MikeDoesUX** [comment]
Hi All!

Also a fan of this feature suggestion! Using the literal github pattern like the one @kolibril13 found as an example would already be a great improvement as-is IMHO. If we want to take it further, I've attached another alternate 'stage' design pattern in case it helps.

![stage](https://user-images.githubusercontent.com/122421048/219326140-4f060599-de7c-4efc-9ff7-9446503766f9.png)

[**Play with prototype here** (so you can feel what it's like to scroll it).](https://www.figma.com/proto/aKgHYyrRwr8B5qdowIwZl7/myst?page-id=0%3A1&node-id=1%3A31&viewport=-1167%2C129%2C0.26&scaling=min-zoom&starting-point-node-id=1%3A31)

My thought process:
1. It might help to perceptually link the frame itself to the outer content more, creating a more obvious "stage with something on it" effect. For this, 100% width on the frame should help (versus just a little border).

2. To dial up the "object on separate stage" feel, I added an inset shadow to the frame and a drop shadow on the 'object' itself. So you're drawn in to something with 3d-object properties.

This 'stage' pattern is generalizable to any time you want to show an _output_, but something like a standard figure should probably not use it (and just have a small frame or just a drop shadow like the callout boxes). Anyway just one idea; feel free to change/ditch!

**Comment by rowanc1** [comment]
This will be closed with https://github.com/executablebooks/myst-theme/pull/80.

Thanks again @kolibril13 and @MikeDoesUX for your help! I will update the docs site shortly!

![image](https://github.com/executablebooks/myst-theme/assets/913249/660df9fe-be3f-43bc-89c5-bd8bc905cf94)
