### ISSUE TITLE
Text formatting role with {underline}`hello` not working in online editor

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystjs#221]
### Which area is this feature request for?

Website User Interface

### Describe the feature you'd like to request

https://myst-tools.org/docs/mystjs/typography
![image](https://user-images.githubusercontent.com/44469195/219103011-7e44bf4e-2204-4f41-bb42-96808dc8daf6.png)
Maybe one can note this in the docs?

**Comment by rowanc1** [comment]
Thanks @kolibril13 this is waiting on #181 to be able to better share all of the directives and roles throughout the various applications (CLI, online demos & jupyter). I think that @fwkoch is planning to merge some of that work in later this week -- we will pick up this ticket as part of that!

**Comment by rowanc1** [comment]
Merged #181 ... working on this now. There are a bunch of moving pieces to get this out the door, but .. they work!! 🚀 

![image](https://user-images.githubusercontent.com/913249/219506849-8cd06a42-3e2a-42c9-9040-2123f4211f78.png)

**Comment by rowanc1** [comment]
Added a new section to the docs, it is now working!

![image](https://user-images.githubusercontent.com/913249/219898979-8347e521-3c4b-415d-8dd1-b654a376f5b8.png)
