### ISSUE TITLE
Making collapsed content accessible for find-in-page search

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystjs#222]
### Which area is this feature request for?

Website User Interface

### Describe the feature you'd like to request

Currently, it's not possible to find text on the website if an admonition is collapsed, e.g. search "npm install" here:
https://myst-tools.org/docs/mystjs/quickstart-myst-websites
and nothing will be found.

This might be a way to get a result: https://developer.chrome.com/articles/hidden-until-found/

**Comment by rowanc1** [comment]
Thanks @kolibril13 -- also noticed this last week. We have fixed it in the `@myst-theme` repo, but the changes haven't made it out to the website yet! I will close this when we update `myst-tools.org` to the latest component.

We are now using `<details>/<summary>` html components, which have better accessibility, and work with find -- as well as auto open, which is all quite nice. :)

![find-in-admonition](https://user-images.githubusercontent.com/913249/219113612-538d69fb-3325-49d0-9ec7-75dbdcee56c2.gif)

**Comment by rowanc1** [comment]
Did not know about `hidden-until-found`, that is slick. I think that we could apply it to the tabs, which currently won't work with the solution I described.

**Comment by rowanc1** [comment]
Do you know of a good way to do this in tabs? I think our tabs could be made more accessible, but I haven't found any examples of the `hidden-unitl-found` trick being used for tabbed-content.

This is the best I have found at the moment:
https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/

**Comment by rowanc1** [comment]
This is now live!! 🚀

![image](https://user-images.githubusercontent.com/913249/219898946-50bc55a3-3038-47ad-91ca-ca072a9a24f4.png)
