### ISSUE TITLE
Inline code within the caption of a `code-block` directive does not render

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystjs#230]
### What version of `mystjs` are you using?

0.1.11

### How did you install myst?

npm

### What operating system are you using?

Mac

### Which area is this feature request for?

Other

### Describe the Bug

In the sandbox at https://myst-tools.org/sandbox , when trying to put inline code in the caption of a code block, it does not render.

See [this sandbox link](https://myst-tools.org/sandbox?tab=demo&myst=VABoAGkAcwAgAGkAcwAgAGMAbwBkAGUALAAgAG0AYQByAGsAZABvAHcAbgAgAHMAdAB5AGwAZQA6AAoAYABgAGAAcAB5AHQAaABvAG4ACgBpAG0AcABvAHIAdAAgAG0AYQB0AHAAbABvAHQAbABpAGIALgBwAHkAcABsAG8AdAAgAGEAcwAgAHAAbAB0AAoACgBwAGwAdAAuAHAAbABvAHQAKABbADEALAAgADIALAAgADMAXQAsACAAWwAxACwAIAAyACwAIAAzAF0ALAAgACcAZwBvAC0AJwAsACAAbABhAGIAZQBsAD0AJwBsAGkAbgBlACAAMQAnACwAIABsAGkAbgBlAHcAaQBkAHQAaAA9ADIAKQAKAGAAYABgAAoACgBCAHUAdAAgAHQAaABpAHMAIABpAHMAIABhACAAYABjAG8AZABlAC0AYgBsAG8AYwBrAGAAIABNAHkAUwBUACAAZABpAHIAZQBjAHQAaQB2AGUAIQAgAEMAaABlAGMAawAgAG8AdQB0ACAAWwBdACgAIwBtAHkALQBwAHIAbwBnAHIAYQBtACkAIABiAGUAbABvAHcAOgAKAAoAYABgAGAAewBjAG8AZABlAC0AYgBsAG8AYwBrAH0AIABwAHkAdABoAG8AbgAKADoAbgBhAG0AZQA6ACAAbQB5AC0AcAByAG8AZwByAGEAbQAKADoAYwBhAHAAdABpAG8AbgA6ACAATQBhAGsAaQBuAGcAIABhACAAcwBpAG0AcABsAGUAIABgAG0AYQB0AHAAbABvAHQAbABpAGIAYAAgAHAAbABvAHQAIAA92MrcLgAKADoAbABpAG4AZQBuAG8AcwA6AAoAOgBlAG0AcABoAGEAcwBpAHoAZQAtAGwAaQBuAGUAcwA6ACAAMwAKAAoAaQBtAHAAbwByAHQAIABtAGEAdABwAGwAbwB0AGwAaQBiAC4AcAB5AHAAbABvAHQAIABhAHMAIABwAGwAdAAKAAoAcABsAHQALgBwAGwAbwB0ACgAWwAxACwAIAAyACwAIAAzAF0ALAAgAFsAMQAsACAAMgAsACAAMwBdACwAIAAnAGcAbwAtACcALAAgAGwAYQBiAGUAbAA9ACcAbABpAG4AZQAgADEAJwAsACAAbABpAG4AZQB3AGkAZAB0AGgAPQAyACkACgBgAGAAYAAKAA%3D%3D)

### Expected Behavior

The inline code should be rendered

**Comment by rowanc1** [comment]
This should be picked up in an upcoming release related to the improved directives #181.

![image](https://user-images.githubusercontent.com/913249/219752163-816fa360-d31b-4f8b-90f6-9f8412c0bb7d.png)

**Comment by rowanc1** [comment]
This is now deployed!! 🚀

Can test out the link again [here](https://myst-tools.org/sandbox?tab=demo&myst=VABoAGkAcwAgAGkAcwAgAGMAbwBkAGUALAAgAG0AYQByAGsAZABvAHcAbgAgAHMAdAB5AGwAZQA6AAoAYABgAGAAcAB5AHQAaABvAG4ACgBpAG0AcABvAHIAdAAgAG0AYQB0AHAAbABvAHQAbABpAGIALgBwAHkAcABsAG8AdAAgAGEAcwAgAHAAbAB0AAoACgBwAGwAdAAuAHAAbABvAHQAKABbADEALAAgADIALAAgADMAXQAsACAAWwAxACwAIAAyACwAIAAzAF0ALAAgACcAZwBvAC0AJwAsACAAbABhAGIAZQBsAD0AJwBsAGkAbgBlACAAMQAnACwAIABsAGkAbgBlAHcAaQBkAHQAaAA9ADIAKQAKAGAAYABgAAoACgBCAHUAdAAgAHQAaABpAHMAIABpAHMAIABhACAAYABjAG8AZABlAC0AYgBsAG8AYwBrAGAAIABNAHkAUwBUACAAZABpAHIAZQBjAHQAaQB2AGUAIQAgAEMAaABlAGMAawAgAG8AdQB0ACAAWwBdACgAIwBtAHkALQBwAHIAbwBnAHIAYQBtACkAIABiAGUAbABvAHcAOgAKAAoAYABgAGAAewBjAG8AZABlAC0AYgBsAG8AYwBrAH0AIABwAHkAdABoAG8AbgAKADoAbgBhAG0AZQA6ACAAbQB5AC0AcAByAG8AZwByAGEAbQAKADoAYwBhAHAAdABpAG8AbgA6ACAATQBhAGsAaQBuAGcAIABhACAAcwBpAG0AcABsAGUAIABgAG0AYQB0AHAAbABvAHQAbABpAGIAYAAgAHAAbABvAHQAIAA92MrcLgAKADoAbABpAG4AZQBuAG8AcwA6AAoAOgBlAG0AcABoAGEAcwBpAHoAZQAtAGwAaQBuAGUAcwA6ACAAMwAKAAoAaQBtAHAAbwByAHQAIABtAGEAdABwAGwAbwB0AGwAaQBiAC4AcAB5AHAAbABvAHQAIABhAHMAIABwAGwAdAAKAAoAcABsAHQALgBwAGwAbwB0ACgAWwAxACwAIAAyACwAIAAzAF0ALAAgAFsAMQAsACAAMgAsACAAMwBdACwAIAAnAGcAbwAtACcALAAgAGwAYQBiAGUAbAA9ACcAbABpAG4AZQAgADEAJwAsACAAbABpAG4AZQB3AGkAZAB0AGgAPQAyACkACgBgAGAAYAAKAA%3D%3D).
