### ISSUE TITLE
Export MarkdownIt plugins

### ISSUE THREAD

**Issue by agoose77** [executablebooks/mystjs#24]
I'm not a TS expert by any means, so please pick me up on things if I've missed something.

[jupyterlab-markup](https://github.com/agoose77/jupyterlab-markup) implements a plugin system that simply provides a JupyterLab-extension point for MarkdownIt plugins. Currently markdown-it-myst creates the MarkdownIt renderer internally, and does not export the plugins for consumption by third-party packages. 

https://github.com/executablebooks/markdown-it-myst/blob/2c186568e645a8cb15051e7a35230dfc1b949aa7/src/index.ts#L20-L29

Would you be able to make these public so that I can wrap them in https://github.com/agoose77/jupyterlab-myst?

**Comment by rowanc1** [comment]
That sounds great, would exporting a function (or a few) that you can put into the `tokenizer.use(blocksPlugin);` work @agoose77?

**Comment by rowanc1** [comment]
Put together a PR that might help with this, let me know if this works for your use case and I can cut a version with the extended exports.

```javascript
import { plugins, roles, directives } from 'markdown-it-myst';

// Somewhere create a markdownit tokenizer:
const tokenizer = MarkdownIt('commonmark', opts.markdownit);

// Later:
tokenizer.use(plugins.math);
tokenizer.use(plugins.blocks);
tokenizer.use(plugins.directives(directives));
tokenizer.use(plugins.roles(roles));
```

I haven't tested too extensively with only having some of the plugins active at once, and haven't tried with other libraries either. Looking forward to helping you integrate!

**Comment by rowanc1** [comment]
Taking a look at the code, I think this should be enough to be getting on with!
https://github.com/agoose77/jupyterlab-myst/blob/main/src/blocks.ts#L7

I will move ahead but leave this open for comment from you when you get a chance.

**Comment by rowanc1** [comment]
The next version of the repo `v0.0.8` is on npm with this change - let me know how it goes!

**Comment by agoose77** [comment]
@rowanc1 nice work, u think we must be on different timezones!

**Comment by rowanc1** [comment]
Makes for a good handoff. :)
Looking forward to seeing if you can get an initial cut going as an MD integration with this! More than happy to contribute in a few weeks!

**Comment by agoose77** [comment]
@rowanc1 if you want to try it out, I have a fork here that is working for me: https://github.com/agoose77/jupyterlab-myst
