### ISSUE TITLE
Rendering of checkbox on website demo

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystjs#244]
### Which area is this feature request for?

Website User Interface

### Describe the feature you'd like to request

checkbox rendering looks like this on the website:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/44469195/219937872-21f1cd81-4f86-4266-9519-76e03ab473f2.png">

**Comment by rowanc1** [comment]
How strange! Will get that sorted, thanks for the report!

**Comment by rowanc1** [comment]
This is fixed in 0.1.19! 🚀

I will get it deployed to the sandbox/docs shortly. Thanks for the report, keep them coming! :)

![image](https://user-images.githubusercontent.com/913249/226794456-8a6820de-bd4a-417e-8466-f3d32cc8a5e6.png)
