### ISSUE TITLE
Handling of "footnoteReference" and "comment" in latex.

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystjs#249]
### Which area is this feature request for?

LaTeX Export

### Describe the feature you'd like to request

Using footnotes:

```
It's used in the wave equation[^myref].
[^myref]: Very useful!
```
results in
`⛔️ Unhandled LaTeX conversion for node of "footnoteReference"`

and footnotes are also not rendered in the pdf.

<br>
<br>
Furthermore, using 

```
<!-- Hello world -->
```
results in 
`⛔️ Unhandled LaTeX conversion for node of "comment"`

Maybe there is a way to replace the ⛔️ by a warning emoji ? https://emojipedia.org/emoji/%E2%9A%A0%EF%B8%8F/
Because I think it's expected that comments won't render to pdf.

<br> 

Script for reproducing this:

```
---
title: Hello

exports:
  - format: pdf
    template: arxiv_two_column
---

+++ {"part": "abstract"}

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa tincidunt dui ut ornare lectus sit amet est placerat.
+++


It's used in the wave equation[^myref].
[^myref]: Very useful!


<!-- Hello world -->
```

**Comment by rowanc1** [comment]
I think we handle `mystComment` rather than `comment` (these should probably be the same thing actually, and changed in the spec because there isn't anything special about a mystComment!).

Surprised we haven't done footnotes, that shouldn't be hard to add! @fwkoch is doing some LaTeX improvements at the moment and hopefully can take a look!

**Comment by rowanc1** [comment]
Looks like @fwkoch has picked up part of this in:
- #255 🚀

**Comment by fwkoch** [comment]
Here's the other half - footnotes!

https://github.com/executablebooks/mystjs/pull/256

**Comment by rowanc1** [comment]
Both of these should now be solved. I will go through and prep another release!

**Comment by rowanc1** [comment]
Released in myst-cli v0.1.17 🚀

**Comment by rowanc1** [comment]
(this will take me a bit longer to get it to show up on myst-tools.org, perhaps next week)

**Comment by rowanc1** [comment]
This actually got deployed to the site just now as there was another bug with iframe height that needed fixing!
