### ISSUE TITLE
Raise errors if node isn't rendered in Tex

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystjs#261]
Currently we raise errors if nodes aren't handled in JATS, this logic is not present in rendering Tex. We should raise those errors!

![image](https://user-images.githubusercontent.com/913249/221058861-be46ed06-5800-422b-91fd-1775a463e372.png)

**Comment by fwkoch** [comment]
The functionality for this is present in `myst-to-tex` and implemented in `myst-cli`, it just wasn't hooked up in the `myst-demo` theme component. Should be resolved here: https://github.com/executablebooks/myst-theme/pull/26

**Comment by rowanc1** [comment]
Nice, didn't realize this was just in the MyST demo! Thanks for the find and fix. :)
