### ISSUE TITLE
Add note to tutorial how to update myst-cli

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystjs#265]
### Which area is this feature request for?

Other

### Describe the feature you'd like to request

It would be nice to have a section in https://myst-tools.org/docs/mystjs/quickstart that describes how to update to the latest version of myst-cli. I think it's `npm update myst-cli` but I don't know npm so well, so I am not sure if this is the supposed way. 

Also, there are some other versions showing from `myst` and `mystjs` which I people (or at least me :D ) might get confused by:
```
jan-hendrik@JanHendriksAir mystjs-minimal-example % npm view myst version
0.0.1-alpha
jan-hendrik@JanHendriksAir mystjs-minimal-example % npm view mystjs version
0.0.15
jan-hendrik@JanHendriksAir mystjs-minimal-example % npm view myst-cli version
0.1.17
jan-hendrik@JanHendriksAir mystjs-minimal-example % 
```

**Comment by rowanc1** [comment]
Hi @kolibril13 -- there is a section here:
https://myst-tools.org/docs/mystjs/installing#updating-myst

I wonder if you want to take a crack at moving this to the quickstart guide? I think it can be duplicated -- and if you want you can use the `{embed}` directive.

Let me know -- otherwise I can take a go at this early next week!

**Comment by kolibril13** [comment]
Hii @rowanc1,

Looking forward to that search field, that's the feature I use most when reading docs :) 
Here is the pr: https://github.com/executablebooks/mystjs/pull/288
(I did not know how to use  {embed} there, so I just copied and pasted the content)

Also, it looks a bit unusual to have two installation guides, but I can see the reason why that's the case and I also don't have a better idea. 
<img width="915" alt="image" src="https://user-images.githubusercontent.com/44469195/222553697-cc8dcb82-4e3f-478d-9ab4-4d25fa6a4f84.png">

**Comment by rowanc1** [comment]
Nice, thank you! It is live!

https://myst-tools.org/docs/mystjs/quickstart#installing-the-myst-cli

Yeah, I agree on the two pages, I am not totally sure that we need the second one anymore at all. The only thing that doesn't have an alternative home is the latex install comments (which aren't very comprehensive anyways). My thinking was that we might have that as a troubleshooting guide/reference material that goes into a lot more depth than the quickstart.

It could also be something like "installing dependencies" or something and merge with the page below it? (latex, npm/node, imagemagik, inkscape).

If you have specific thoughts on how to improve this, always welcome PRs! :)

Agree, I miss search a lot ... it will get done!

**Comment by rowanc1** [comment]
I am going to close this specific issue! Thanks again for the PR.

And -- we should document the embed syntax @fwkoch, it is pretty cool. :)

**Comment by kolibril13** [comment]
> troubleshooting guide/reference 

sounds good, that would probably be a bit similar to an FAQ.
Maybe these resources can also be linked to at the end of the quickstart installation chapter.
