### ISSUE TITLE
Starting server sometimes results in an infinity loop of:`💥 Triggered full site rebuild `  

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystjs#266]
### What version of `mystjs` are you using?

`myst -v`  gives v0.1.11, but `npm view myst-cli` gives myst-cli@0.1.17

### How did you install myst?

npm

### What operating system are you using?

Mac

### Which area is this feature request for?

Command Line Interface

### Describe the Bug

Starting a server with `myst start` sometimes results in a loop of `💥 Triggered full site rebuild ` . 
I don't understand the pattern when this comes or not comes. 
In the screen recording, you can be that loop at 0:24 and at 1:02

https://user-images.githubusercontent.com/44469195/221173959-c09ee4c4-e5af-4d3c-98dd-634ada3f6d08.mov

Maybe that has something to do with refreshing the page or with focusing the mouse on the browser?
Most of the time it does not come, so it does not bother me too much, I just wanted to let you know!

**Comment by rowanc1** [comment]
@fwkoch and I have seen this a few times as well, neither of us have been able to reliably recreate it though.

I am not quite sure what the solution should be, perhaps we should ensure we don't trigger another full re-build if there is a build in progress, I think that would be fine, and probably address this? Curious on your thoughts @fwkoch!

**Comment by rowanc1** [comment]
@kolibril13 -- @fwkoch and I are thinking that #286 has fixed this. I haven't seen it again at least on testing on a variety of projects!!

We will aim to release a patch tomorrow and will optimistically close the issue, and we can revisit if the changes didn't fully address the problem.

Thanks for your help in tracking this down.

**Comment by kolibril13** [comment]
Just tested the latest version (v0.1.18), this bug is fixed now! 🎉

**Comment by rowanc1** [comment]
Yay! Thanks for closing, glad that this is working now!
