### ISSUE TITLE
Add a demo page

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystjs#27]
The JS `markdown-it` package has a nice [syntax demo page](https://markdown-it.github.io/) that comes with some pre-defined syntax and also lets you update the syntax manually to see how it behaves. I think it'd be useful if we had a simple page like this once we have the JS parser/renderer in good shape.

cc @rowanc1 who I believe showed off something like this a few months ago 🤔🤔

**Comment by rowanc1** [comment]
It is still accessible through the readme, live demo badge. Will continue to integrate the demos through the docs!

**Comment by rowanc1** [comment]
This will be throughout the documentation for the new package as well as a standalone page in the docs to show a playground. You will be able to show the preview, ast, and html outputs. See for example:

![image](https://user-images.githubusercontent.com/913249/153925749-c0fe5a7c-f377-4aa7-8714-6274e144782c.png)

I will leave this up until we get the stand-alone demo page a bit nicer.

---

At the next team meeting I think @fwkoch and I can show what we have done with the docs here and have a conversation about where the content should live. I have taken some inspiration from both the jupyterbook and myst-parser pages and improved it with live demos and additional pointers and explanations. Some of this is less specific to `mystjs` and is likely hitting at a stand-alone repository for the `myst-spec`, which includes tests for new implementations and the canonical documentation of myst.

**Comment by rowanc1** [comment]
I am going to close this, now that the docs page is starting to have many more demos!

See:
https://js.myst.tools/guide/typography
