### ISSUE TITLE
Unresponsive content when sidebar is collapsed

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystjs#276]
### What version of `mystjs` are you using?

latest

### How did you install myst?

npm

### What operating system are you using?

Mac

### Which area is this feature request for?

Website User Interface

### Describe the Bug

When the sidebar is collapsed on a narrow screen, the content that is close to the left side of the window becomes unresponsive, as can be seen in this screen recording:

https://user-images.githubusercontent.com/44469195/221351897-1a5836ad-64f0-45bf-9db3-b5561c84d20b.mov

<br>

Here is a sample project for testing media-content:  
https://github.com/kolibril13/mystjs-media-example

**Comment by rowanc1** [comment]
Thanks for this bug report -- I made a change to the mobile nav, but that is now open + not visible on all variants! I will get that removed in `@myst-theme`.

**Comment by rowanc1** [comment]
Also tracking here:
https://github.com/executablebooks/myst-theme/issues/25

**Comment by rowanc1** [comment]
Bug is fixed and merged, just needs a release.

**Comment by rowanc1** [comment]
Have released and updated the website. To use this locally, `myst clean --templates` and then `myst start`!

Thanks again for reporting this, silly mistake -- however, it is a prelude to some very cool upcoming features for article layout. 🚀

![grids](https://user-images.githubusercontent.com/913249/222334283-0f0680a4-79af-4fe0-8996-0e274895ccbf.gif)
