### ISSUE TITLE
Myst parser does not handle the `code-cell` directive

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystjs#284]
A `code-cell` directive is used in MyST notebook. 

This is defined [here in the jupyterbook docs](https://jupyterbook.org/en/stable/file-types/myst-notebooks.html#create-a-myst-notebook-with-jupytext) in terms of converting from `.ipynb`  to MyST `.md` using `juyptertext` that appears to be where code-cell is defined?

currently mysjs does not parse this directive, byt myst-nb does. Being able to parse and support existing MyST notebooks would be very cool.

**Comment by stevejpurves** [comment]
This probably also means extending the docs in terms of adding a subsection on the directive, and a section on working with MyST notebooks. In fact, if this is a migration pathway for people onto the js cli, then perhaps there should be a guide?

**Comment by rowanc1** [comment]
This was released in 0.1.18! 🚀
