### ISSUE TITLE
🔧 Refactor image conversion transform

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/mystjs#287]
The [transform to convert image formats](https://github.com/executablebooks/mystjs/blob/main/packages/myst-cli/src/transforms/images.ts#L208) is an immense wall of code, with significant repetition and opaque logic tied up in nested if statements. It is also entirely untested. This means supporting new image types and new conversions between types is ... not great.

This transform needs a refactor so:
- the different image format inputs/outputs are defined declaratively
- the actual conversion functions (imagemagic, inkscape) are well organized
- logic to choose specific conversions is centralized
- error messages are centralized
- functions are small and testable

**Comment by rowanc1** [comment]
Thanks for documenting this @fwkoch.

**Comment by rowanc1** [comment]
Released in v0.1.19 🚀
