### ISSUE TITLE
ERROR: Unknown directive type "mermaid"

### ISSUE THREAD

**Issue by sbonaretti** [executablebooks/mystjs#296]
Hi! 

I am trying to use the new [mermaid diagrams](https://myst-tools.org/docs/mystjs/diagrams), but I get this error: `ERROR: Unknown directive type "mermaid"`

The output of:      
```bash
 jupyter-book --version
``` 
is: 
```
Jupyter Book      : 0.15.0
External ToC      : 0.3.1
MyST-Parser       : 0.18.1
MyST-NB           : 0.17.1
Sphinx Book Theme : 1.0.0
Jupyter-Cache     : 0.5.0
NbClient          : 0.5.13
```

What am I missing? Thanks a lot!!!

Serena 

PS: Is it possible to use mermaid diagrams also in Curvenote? What would the command be? I have tried a bunch of things, but it didn't work out. Thanks!!!

**Comment by agoose77** [comment]
Hi @sbonaretti, thanks for opening an issue!

We're currently consolidating our documentation to make it clearer which tools support which features. As you can imagine, this is a natural growing pain of MyST becoming supported by multiple initiatives!

You're using Jupyter Book, which is a distinct set of tools from `mystjs`. There _is_ a Sphinx extension (which is what powers Jupyter Book). The extension repository can be found [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiz8OON3Nj9AhXBTEEAHQSEAFEQFnoECBAQAQ&url=https%3A%2F%2Fgithub.com%2Fmgaitan%2Fsphinxcontrib-mermaid&usg=AOvVaw3Nbji9tuNThOfl036GxYOi). 

- To install this extension, you need the `sphinxcontrib-mermaid` package [from PyPI ](https://pypi.org/project/sphinxcontrib-mermaid/)/ conda-forge
- To load the extension, you would need to modify your `_config.yml`:
	```yaml
	sphinx:
	  extra_extensions:
	    - sphinxcontrib.mermaid
	```

If you're building a LaTeX document, you would also need to have the mermaid CLI installed. I suspect you do not need this, so I'll refrain from describing that process just yet. But, let me know if I've made a poor assumption here!

**Comment by sbonaretti** [comment]
Cool! It works!!! Thanks so much for replying this quickly and for all your work!

**Comment by agoose77** [comment]
Fantastic news! I'll close this issue, but please feel free to re-open it if you have any further issues or questions :)
