### ISSUE TITLE
escape hash/pound `#` symbols in urls

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystjs#297]
### What version of `mystjs` are you using?

0.1.17 + dev

### How did you install myst?

npm

### What operating system are you using?

Mac

### Which area is this feature request for?

Export: LaTeX or PDF

### Describe the Bug

If a use contains a hash/pound symbol, as is common when bookmarks are used:

`https://mydomain.com/path/name#bookmark` this gets rendered as-is into latex on `myst build --tex` and the resulting pdf build will error

### Expected Behavior

`#` symbols has special meaning in a latex command and should be escaped.

**Comment by fwkoch** [comment]
@stevejpurves can you give a bit more detail on how to reproduce this? Trying out a few contexts where links are used, it seems to escape the `#` where I would expect, and I saw no problems with PDF build:

![image](https://user-images.githubusercontent.com/9453731/225489703-cdfd7c68-6c62-4236-afc5-14b4626e365f.png)

**Comment by stevejpurves** [comment]
@fwkoch found the concrete example!!

```
\begin{figure}[!htbp]
\centering
\includegraphics[width=0.7\linewidth]{files/qgIKQkOFmSWbOdFZN8YZ-b2a87b9873e7faa24764c125b03db6e0.png}
\caption{Huidige vergunde grondwateronttrekkingen in het studiegebied. Bron: \href{https://www.dov.vlaanderen.be/geonetwork/srv/eng/catalog.search#/metadata/397d5188-50a0-45f4-9ce2-f7baf7d77422}{DOV}}
\label{ygtjinrrtm}
\end{figure}
```

the following chunk of latex causes errors during compilation like this:


```
l.85 ...97d5188-50a0-45f4-9ce2-f7baf7d77422}{DOV}}
                                                  
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

./main.tex:85: Illegal parameter number in definition of \GTS@GlobalString.
<to be read again> 
                   /
l.85 ...97d5188-50a0-45f4-9ce2-f7baf7d77422}{DOV}}
                                                  
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.

./main.tex:85: Illegal parameter number in definition of \@tempa.
<to be read again> 

...blah blah usual latex endless blah....
```

escaping the `#` removes the error

**Comment by fwkoch** [comment]
Ah thanks, super helpful. Looks like this error occurs when the href is inside any macro (not just `caption`), so even this errors on PDF build:
```
*[link](https://example.com#my-example)*
```

**Comment by rowanc1** [comment]
Fixed!!
