### ISSUE TITLE
list table containing a `role` in the caption does not render to latex

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/mystjs#300]
### What version of `mystjs` are you using?

0.1.17 + dev

### How did you install myst?

npm

### What operating system are you using?

Mac

### Which area is this feature request for?

Export: LaTeX or PDF

### Describe the Bug

it is possible to write a list table with a role in the title/caption but this will then no render as expected to react, html or latex.

See: https://myst-tools.org/sandbox?tab=demo&myst=CgBgAGAAYAB7AGwAaQBzAHQALQB0AGEAYgBsAGUAfQAgAHMAbwBtAGUAIAB0AGkAbABlACAAbwByACAAYwBhAHAAdABpAG8AbgAgAHcAaQB0AGgAIABhACAAcgBvAGwAZQAgACgAUgB7AHMAdQBwAH0AYAAyAGAAKQAKADoAaABlAGEAZABlAHIALQByAG8AdwBzADoAIAAxAAoAOgBuAGEAbQBlADoAIABoAHoAbwBtAEMAWQBhAGYAQgBZAAoACgAtACAALQAKAAoAIAAgAC0AIABSAE0AUwBFACAAKAB0AC4AaABhAHsAcwB1AHAAfQBgAFwALQAxAGAAIAApAAoACgAgACAALQAgAFIAUgBNAFMARQAgACgALQApAAoACgAgACAALQAgAFIAewBzAHUAcAB9AGAAMgBgACAAKAAtACkACgAKAC0AIAAtACAAZwByAGEAcwAKAAoAIAAgAC0AIAAzAFwALgAwADcACgAKACAAIAAtACAAMABcAC4AMgAzAAoACgAgACAALQAgADAAXAAuADEAMgAKAAoAYABgAGAA 

### Expected Behavior

we expect to render out the table in any of the supported forms, and for the directive and role to be properly processed.

**Comment by rowanc1** [comment]
The fence gets broken if there are other `` ` ``s in the first line of a backtick fence.

This is CommonMark behaviour, which can be side-stepped with a colon fence ([demo](https://myst-tools.org/sandbox?tab=demo&myst=OgA6ADoAewBsAGkAcwB0AC0AdABhAGIAbABlAH0AIABzAG8AbQBlACAAdABpAGwAZQAgAG8AcgAgAGMAYQBwAHQAaQBvAG4AIAB3AGkAdABoACAAYQAgAHIAbwBsAGUAIAAoAFIAewBzAHUAcAB9AGAAMgBgACkACgA6AGgAZQBhAGQAZQByAC0AcgBvAHcAcwA6ACAAMQAKADoAbgBhAG0AZQA6ACAAaAB6AG8AbQBDAFkAYQBmAEIAWQAKAAoALQAgAC0ACgAKACAAIAAtACAAUgBNAFMARQAgACgAdAAuAGgAYQB7AHMAdQBwAH0AYABcAC0AMQBgACAAKQAKAAoAIAAgAC0AIABSAFIATQBTAEUAIAAoAC0AKQAKAAoAIAAgAC0AIABSAHsAcwB1AHAAfQBgADIAYAAgACgALQApAAoACgAtACAALQAgAGcAcgBhAHMACgAKACAAIAAtACAAMwBcAC4AMAA3AAoACgAgACAALQAgADAAXAAuADIAMwAKAAoAIAAgAC0AIAAwAFwALgAxADIACgA6ADoAOgA%3D)).

I think this is probably a documentation issue, and we should not encourage directive arguments to have markdown in them. I have run into this countless times with the caption of a table which can often be technical having citations and other roles.

**Comment by fwkoch** [comment]
Tiny update to docs for this: https://github.com/executablebooks/mystjs/pull/308

**Comment by fwkoch** [comment]
Closing this issue, as I don't think we are going to fix the underlying problem in markdown-it. If this continues to be a big problem, even with documentation etc, we can re-open.
