### ISSUE TITLE
Support wildcard extensions for images

### ISSUE THREAD

**Issue by thesamovar** [executablebooks/mystjs#304]
### Which area is this feature request for?

MyST Markdown Syntax

### Describe the feature you'd like to request

Sphinx has a neat feature where you can write ``filename.*`` in an image directive and it will pick the (for example) ``.png`` or ``.pdf`` version depending on the output build format. This would be great to support here too.

### Describe alternatives you've considered

I'll probably write a preprocessor build script to hack this in the short term, but it would be nice to make it automatic.

**Comment by rowanc1** [comment]
Thanks @thesamovar! As you note @fwkoch I think this would go well to tackle with #287 as well! We would likely need to rank the image formats by the export type (e.g. PDF for latex should be native, but png preferred in the web, etc.).

@thesamovar there is built in image conversion at the moment, if you want to change the extension to `pdf`, myst should use imagemagik or inkscape to do the conversion for you. Regardless, this is a helpful feature if you want more control over what images are actually used.

**Comment by thesamovar** [comment]
Oh I didn't know that - that's awesome. So for my case at least I'll just switch to using pdfs everywhere. Thanks!

**Comment by rowanc1** [comment]
There is also conversion to `webp` if you have that installed as well, which ensures better initial load of the site when publishing! Let us know if you have any problems with the `.pdf` conversion, I don't think we have that totally nailed across all operating systems/versions.

**Comment by rowanc1** [comment]
@fwkoch refactored our whole image translation layer. 🎉 Some new features and docs coming soon!

I will circle back on this issue when we release! 🔜

![image-translation](https://user-images.githubusercontent.com/913249/226753175-147805af-97d9-42e5-a4e8-1054ee04e712.gif)

![image](https://user-images.githubusercontent.com/913249/226753155-d9516adb-0c1b-47ca-aa30-2d4ae02ce22f.png)

**Comment by rowanc1** [comment]
@thesamovar this is released in v0.1.19 🚀

Let us know how it works out for you please! :)
