### ISSUE TITLE
tsconfig package content usage?

### ISSUE THREAD

**Issue by echarles** [executablebooks/mystjs#344]
the `tsconfig` folder contains the base tsconfig.json which makes sense, but also 3 other files `nextjs.json`, `react-library.json` and `remix.json` - https://github.com/executablebooks/mystjs/tree/bc466578af3c54341d4008755bb9d82f5ad28672/packages/tsconfig

Those 3 files don't seem to be used in this repository, and the tsconfig is not published, so probably also not used somewhere else.

Should they be simply removed?

**Comment by rowanc1** [comment]
Hi @echarles  -- yes these can be deleted. This was a remnant of sharing source with the theme last year, we haven't done a pass at cleaning this up.

Happy to take a PR for this! :)

**Comment by echarles** [comment]
@rowanc1 here we go https://github.com/executablebooks/mystjs/pull/346
