### ISSUE TITLE
`myst` command not found on Windows 10

### ISSUE THREAD

**Issue by lrq3000** [executablebooks/mystjs#382]
### What version of `mystjs` are you using?

latest (just installed)

### How did you install myst?

npm

### What operating system are you using?

Windows

### Which area is this feature request for?

Command Line Interface, Installation

### Describe the Bug

I just tried the install instructions given in the README on a clean node.js install on Windows 10.

After `npm install -g myst-cli`, I get the following output:

```
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated mdast@3.0.0: `mdast` was renamed to `remark`
npm WARN deprecated wikidata-sdk@8.1.1: wikidata-sdk has been renamed wikibase-sdk

changed 422 packages in 48s

101 packages are looking for funding
  run `npm fund` for details
```

I then try to launch `myst init`, but get a `myst command not found` error.

Note that my nodejs folder is in the path, I can call both the `npm` and `node` commands, but not `myst`, even after relaunching my terminal.

Keep in mind I am a noob in javascript and node.js. I know how to setup a static site generator through Gatsby and that's about it 😅 

### Expected Behavior

`myst init` should initialize a MyST repository.

Is there an alternative to call the `myst` command through `npm` or `node` maybe?

**Comment by rowanc1** [comment]
Thanks for the bug report @lrq3000, I am not an expert here and don't have easy access to testing on a windows machine. The install looks fine! My guess is that where ever your global node packages are is not on your system path, so it isn't picking myst up. Figuring out where that is and adding it to your path should hopefully fix it?!

Alternatively if you have `npx` (I think it comes with npm/node!?!), you could try:\
`npx myst -v`

**Comment by lrq3000** [comment]
Awesome @rowanc1 ! Yes `npx myst -v` works fine, (and I did not install npx beforehand so it came bundled with nodejs), I'll go with that to use mystjs! :D

**Comment by rowanc1** [comment]
Nice! Glad that works. Keep the issues rolling in. :)

Happy writing!
