### ISSUE TITLE
Hiding notebooks on GitHub pages

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystjs#434]
### Which area is this feature request for?

Other

### Describe the feature you'd like to request

I'm thinking of writing a physics script in mystjs and hosting it at https://kolibril13.github.io/myst-physics-script/
That works great so far!
Now, I'd like to hide the Jupyter notebook from the table of conent and only show the conent written in markdown.
Is this possible already?
I guess it has to do something with these lines in myst.yml , however I could not find a solution for that yet.
https://github.com/kolibril13/myst-physics-script/blob/main/myst.yml#L14-L16
Any help would be greatly appreciated :)

**Comment by KyleTCL** [comment]
This is already possible, see [here](https://mystmd.org/guide/table-of-contents).

You have to explicitly include chapters by their path in the `_toc.yml` (see example in the link). Otherwise, make a hidden folder and put your notebook in the hidden folder, they should not be included.

**Comment by kolibril13** [comment]
Hi @KyleTCL , thank you so much for this quick reply!
Indeed, that worked! :)

**Comment by rowanc1** [comment]
Glad that works for you @kolibril13 -- thanks for your help @KyleTCL!

**Comment by kolibril13** [comment]
Just played a bit more around with it, and @rowanc1, may I ask two more questions:

When I add only the `_toc.yml`file, I get the error `The table of contents defined in "_toc.yml" could not find file "index" defined as the "root:" page. Please ensure that one of these files is defined:
- index.md
- index.ipynb
- index.tex
`

1. can I have a `_toc.yml` without an index file?
2. When I create the index.md file, everything works fine. Is there a way I can have the table of content displayed in that index.md file? I could not find anything related to that on the docs.

**Comment by rowanc1** [comment]
Always ask questions, happy to help out! :)

1. Currently they need to have an index, this is what is loaded on the bare domain or project, `my-site.com`. The index page has a few special things that need to happen to it, which is why I think the JupyterBook `_toc.yml` spec treats it differently.
2. Are you maybe thinking about a directive like `toctree` ([in sphinx](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree))? That is currently not implemented yet, keeping a list of these sorts of improvements here #189.

**Comment by kolibril13** [comment]
Hi Rowan, that's good to know, and yes, something like a toctree would be awesome to have!

And another thing I've noted: Now that the notebook is not any more present in the _toc.yml file, the linked assets are not shown on other pages anymore. 
Is there a way I can still use the `#| label: my-vid-embedded` assets from the notebook in a myst chapter without including the notebook itself to the toc?
I think that would be an amazing feature!

**Comment by kolibril13** [comment]
@rowanc1 One more observation:

Even when I have the notebook in the toc, the linking to labeled assets from the notebook on the static webpage does not work (It works though if I start the myst server with myst start).
```
chapters:
  - file: ./01-magnus.md
  - file: ./02-euler.md
  - file: ./media_notebook.ipynb
  ```

Linking on static webpages currently works only when I don't have the _toc file at all.

**Comment by kolibril13** [comment]
...interesting, now it also does now work any more even on static pages without the _toc file.
I'll investigate this further.
