### ISSUE TITLE
Embedded video from notebook do not show anymore on static GitHub page

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystjs#441]
### What version of `mystjs` are you using?

v1.0.3

### How did you install myst?

npm

### What operating system are you using?

Mac

### Which area is this feature request for?

Other

### Describe the Bug

I have a notebook with an embedded video (https://github.com/kolibril13/okapi/blob/main/media_notebook.ipynb?short_path=9bf3cf3#L63), which has the label `#| label: my-vid-embedded`.
2 weeks ago (on Jun 16, 2023), I pushed that notebook to GitHub pages using the workflow described here:
https://mystmd.org/guide/deployment#deploying-to-github-pages 
and the video is displayed in the myst document correctly on GitHub pages
https://kolibril13.github.io/okapi/

I just tried to reproduce this in another project, but by today, displaying linked videos on static pages does not work anymore. I made a 100% identical copy of the repo, and it did not work, so I assume it must be related to version updates in GitHub actions.

### Expected Behavior

Cross-referenced embedded videos should be displayed on Github Pages.

### To Reproduce

1. Forking this repository https://kolibril13.github.io/okapi/ and activate github actions.
2. Visit the webpage, the video will render correctly.
3. Make a commit to that fork, this will trigger the ci.
4. Visit the github pages page again e.g. https://octoframes.github.io/okapi/ -> now the video won't show anymore.

<img width="712" alt="image" src="https://github.com/executablebooks/mystjs/assets/44469195/9d149b4d-f935-45d6-8ac8-cc0137c5032c">

It would be awesome if this feature could be enabled again! :)

**Comment by kolibril13** [comment]
I just did some more testing on Image, GIF and Video in this minimal example repo:  
https://github.com/Octoframes/myst-online-media-testing

Images and GIFs are linked correctly, it's only the video that is not displayed, as can be seen here:
https://octoframes.github.io/myst-online-media-testing/hello

**Comment by rowanc1** [comment]
Thanks for the bug report! @stevejpurves, I think this is likely the changes that we have made to `thebe` as we get things ready for being attached to live kernels?

**Comment by kolibril13** [comment]
Hey @rowanc1 , thanks for your quick reply :)
Just did some more testing, SVGs are broken as well:
https://github.com/Octoframes/myst-online-media-testing/blob/main/media_notebook.ipynb
https://octoframes.github.io/myst-online-media-testing/hello
<img width="716" alt="image" src="https://github.com/executablebooks/mystjs/assets/44469195/5cb773c9-edd9-41b5-be19-921634837a1b">

**Comment by stevejpurves** [comment]
ok - i think the recent change in thebe to force explicit creation of a rendermine factory might have impacted this. I'll take a look next!

**Comment by stevejpurves** [comment]
update: looks like this is actually an issue with how `thebe-core` is now loaded (which was also changes recently) and it's looking in the wrong location.

![image](https://github.com/executablebooks/mystjs/assets/1473646/b12f0ea9-681e-41e0-a63b-68b085556693)

**Comment by rowanc1** [comment]
We will get this deployed shortly and it should start working again!

**Comment by stevejpurves** [comment]
tested and working on a fork of your repo @kolibril13 https://stevejpurves.github.io/myst-online-media-testing/hello

**Comment by rowanc1** [comment]
It won't work yet -- hoping that we can release this later today! I will follow up here when it is deployed!

**Comment by kolibril13** [comment]
Thanks for the response! Your support is absolutely awesome :)

**Comment by rowanc1** [comment]
A rerun of the github action should fix things now!

🐶 🚰 📺 🚀 

![image](https://github.com/executablebooks/mystjs/assets/913249/89db87a8-99b0-4625-b2af-e860290a89ae)

**Comment by kolibril13** [comment]
That's awesome!!!
I've just tested this for some more image, video, gif, svg, dataframe and tweet,  and it's all working out of the box! :)
https://octoframes.github.io/myst-online-media-testing/hello
<img width="1078" alt="image" src="https://github.com/executablebooks/mystjs/assets/44469195/d2e9da9b-e5ac-4425-8427-3a0b6396aabc">
