### ISSUE TITLE
Support for colon fences

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/mystjs#54]
### Context

A lot of the existing jupyter book content has these, and is not rendered using mystjs.

### Proposal

Looking forward to knowing more about where in the current tools we can implement this. I think it might be in the docutils library?

**Comment by agoose77** [comment]
Cool! Is the idea to remove the same plugin from https://github.com/executablebooks/markdown-it-myst-extras?

**Comment by rowanc1** [comment]
Oh man, wish that either @chrisjsewell or I had caught that in the review. Wasn't aware that this was already ported. Thanks for pointing it out.

I think the best thing to do is take it out of docutils, release a new version, and rearrange the import in mystjs.

**Comment by rowanc1** [comment]
Ok, this cleans that up:

- https://github.com/executablebooks/markdown-it-docutils/pull/41

**Comment by rowanc1** [comment]
Ok, this is all fixed up in #56 and confirmed that it is working! :)

Thanks @agoose77 for the catch here.
