### ISSUE TITLE
Hover pop-ups don't break out of containers in admonitions or example blocks

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystjs#57]
### Describe the bug

When an example or an admonition shows off a hover pop-up, it doesn't properly break out of its container. 

### Reproduce the bug

For example, in: https://js.myst.tools/guide/cross-references#directive-targets

![image](https://user-images.githubusercontent.com/1839645/191381394-eedd5f9f-f49f-4111-adb9-cc77bf43d522.png)

**Comment by rowanc1** [comment]
Love the issues coming in, thank you! :)

I will get this pushed out soon!

![image](https://user-images.githubusercontent.com/913249/191400099-ec92f759-5aa0-49d0-9180-407a19698e0f.png)


There was some reason that I hid content-overflow, but can't remember now, so will fix the regression when it comes up. This will also fix wiki link hovers in the demos!

**Comment by rowanc1** [comment]
Also works for hover! Will ideally be live tomorrow, and will close the issue then.

![image](https://user-images.githubusercontent.com/913249/191401489-7ed17459-3b6a-4749-a2ac-7c850b4d4fa1.png)

**Comment by rowanc1** [comment]
Fixed and deployed!
