### ISSUE TITLE
Favicon for mystjs should use the MyST logo

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystjs#58]
### Describe the bug

The favicon for js.myst.tools uses the curvenote logo. Instead it should use the myst logo!

![image](https://user-images.githubusercontent.com/1839645/191381846-a8cc2eec-7c43-458c-8f04-ed71674829b9.png)

### Reproduce the bug

![image](https://user-images.githubusercontent.com/1839645/191381761-4fa48780-7af6-4a6d-b31d-81d6e814456c.png)

**Comment by rowanc1** [comment]
Totally agree! It is something we have been putting off for a bit as we need to dynamically serve the favicon.

Thanks for the report, pushes it higher on my priority list. :)

**Comment by rowanc1** [comment]
Quick update on this, we are ripping out the theme in the next two weeks (current [plan here](https://github.com/executablebooks/meta/issues/838)) and this should be addressed in that chunk of work!

**Comment by echarles** [comment]
> There are a lot of cleanups and generalizations still to do on this front, but I am going to close this specific issue for now!

@rowanc1  The new deployed theme on https://www.myst.tools looks great.

I have just tried to apply the `myst-tools-theme` from https://github.com/curvenote/myst-tools-theme but CSS fails to load. Any reproducible step to make it work before a more general solution is available?

**Comment by rowanc1** [comment]
Hm, not sure, it should build:css in the sub package (src). Maybe a platform or windows thing? You could try executing that script specifically (build:css), it uses tailwind.

**Comment by echarles** [comment]
ran build and build:css in the theme/theme (after replacing the existing ones with the myst-tools-theme source code), but still  same result. I guess a configuration is welcome to allow the definition of the theme. Is this what you were thinking at?
