### ISSUE TITLE
Clarify that this is pre-alpha software

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystjs#61]
### Context

For now, we do not want to make any public commitments about the specific structure, spec, features, etc of this repository. We are using it to explore what a myst implementation in js might look like, but there isn't a clear message to others about the "development state" of the repository. This might lead to confusion about what to expect.

### Proposal

We should put banners in the mystjs documentation and README that make it clear what state the project is in. I suggest something like:

> **Note** **Unstable codebase!**
> This project is in a pre-alpha state. It is being used to explore a MyST implementation in JavaScript, but will likely change significantly and rapidly. It is being developed by a small team of people on the Executable Books Project, and may make rapid decisions without inclusive discussion. We will update this documentation when the state of the project has stabilized.

**Comment by rowanc1** [comment]
We have added this to the main page of the documentation, and updated a few other places around the docs where there are some issues, especially that @kai-tub ran into with jtex (sorry!).

Closing this as the notice is now live on the site!
